default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: pass # comes from docker-compose

development:
  <<: *default
  host: mysql # same as docker container name
  database: api_development

test:
  <<: *default
  host: mysql # same as docker container name
  database: api_test

production:
  <<: *default
  timeout: 5000
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>
  database: <%= ENV.fetch("DB_NAME") { "api_production" } %>
  socket: "<%= ENV.fetch("DB_SOCKET_DIR") { '/cloudsql' } %>/<%= ENV["INSTANCE_CONNECTION_NAME"] %>"
