test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google:
  service: GCS
  project: artaku
  credentials: <%= Rails.root.join("config/gcs_keys.json") %>
  bucket: artaku_production
